export enum SettingsActionType {
  UPDATE_ASIGNEE = 'SETTINGS:UPDATE_ASIGNEE',
  TOGGLE_SETTING = 'SETTINGS:TOGGLE',
  UPDATE_PREFERENCES = 'SETTINGS:UPDATE_PREFERENCES',
}

export enum SettingsKeys {
  CREATE_TESTS = 'CREATE_TESTS',
  GENERATE_CODE_TESTS = 'GENERATE_CODE_TESTS',
  GENERATE_UI_EXAMPLES = 'GENERATE_UI_EXAMPLES',
  LABEL_TRANSLATIONS = 'LABEL_TRANSLATIONS',
}
